name: Build OpenSiv3D Library

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Clone OpenSiv3D (v0.6.15)
        run: git clone --depth=1 --branch v0.6.15 https://github.com/Siv3D/OpenSiv3D.git External/OpenSiv3D

      - name: Download and extract Boost headers (1.74.0)
        shell: pwsh
        run: |
          curl -L -o boost.zip https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/boost_1_74_0.zip
      
          # 過去の展開が残っていたら削除
          #if (Test-Path "boost_1_74_0") {
          #  Remove-Item -Recurse -Force "boost_1_74_0"
          #}
      
          # zip を展開（PowerShell 標準コマンド）
          Expand-Archive -Path "boost.zip" -DestinationPath "."
      
          # OpenSiv3D が期待する場所に boost フォルダだけコピー
          $target = "External/OpenSiv3D/Dependencies/boost_1_74_0/boost"
          if (-Not (Test-Path $target)) {
            New-Item -ItemType Directory -Path $target | Out-Null
          }
          Copy-Item -Recurse -Force "boost_1_74_0/boost" $target

      - name: Build OpenSiv3D.lib
        shell: cmd
        run: |
          msbuild External\OpenSiv3D\WindowsDesktop\Siv3D.vcxproj ^
            /p:Configuration=Release ^
            /p:Platform=x64

      - name: Archive built library
        uses: actions/upload-artifact@v4
        with:
          name: Siv3D-lib
          path: |
            External/OpenSiv3D/Build/lib/x64/Release/Siv3D.lib
