name: Manual Build with Civ3D

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
        CI: true

    steps:
      - name: Checkout repository (with submodules if needed)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Clone Civ3D (or OpenSiv3D) source into External folder
        run: git clone --depth=1 --branch v0.6.15 https://github.com/Siv3D/OpenSiv3D.git External/Siv3D

      #- name: Inject .vcxproj.user with include paths
      #  shell: pwsh
      #  run: |
      #    $projPath = "${{ github.workspace }}\game-3d\game-3d.vcxproj.user"
      #    $content = @'
      #    <?xml version="1.0" encoding="utf-8"?>
      #    <Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      #      <PropertyGroup>
      #        <IncludePath>$(ProjectDir)..\External\Siv3D\include;$(ProjectDir)..\External\Siv3D\include\ThirdParty</IncludePath>
      #      </PropertyGroup>
      #    </Project>
      #    '@
      #        Set-Content -Encoding UTF8 -Path $projPath -Value $content
      
      - name: Build game project
        shell: cmd
        run: |
          msbuild game-3d\game-3d.vcxproj ^
            /p:Configuration=Release ^
            /p:Platform=x64

      - name: Upload to GitHub Release (auto-tag)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: manual-${{ github.run_id }}
          name: ${{ github.event.inputs.release_name || format('Manual Release \#{0}', github.run_number) }}
          files: "game-3d/App/game-3d(debug).exe"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}