name: Build Siv3D App on Windows

on:
  workflow_dispatch:

env:
  # VS ソルーションファイル (.sln) へのパス
  SOLUTION_FILE_PATH: "./game-3d.sln"
  # App フォルダのパス
  APP_PATH: "./game-3d/App"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    # ビルドする
    - name: Setup Siv3D and build
      uses: Ryoga-exe/Siv3D-Actions@v2
      with:
        solution-path: ${{ env.SOLUTION_FILE_PATH }}

    # Artifacts にアップロードする
    - name: Publish App
      uses: actions/upload-artifact@v3
      with:
        name: App
        path: |
          ${{ env.APP_PATH }}
          !${{ env.APP_PATH }}/engine
          !${{ env.APP_PATH }}/AS_DEBUG
          !${{ env.APP_PATH }}/Screenshot
          !${{ env.APP_PATH }}/*.ico
          !${{ env.APP_PATH }}/Resource.rc