name: Manual Build with Civ3D

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (with submodules if needed)
        uses: actions/checkout@v4

      - name: Install dependencies (CMake, Ninja, 7zip)
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          choco install 7zip -y

      - name: Clone Civ3D (or OpenSiv3D) source into External folder
        run: git clone --depth=1 --branch v0.6.15 https://github.com/Siv3D/OpenSiv3D.git External/Siv3D

      - name: Build project with MSBuild
        run: |
          msbuild game-3d\game-3d.vcxproj `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:IncludePath="${{ github.workspace }}\External\Siv3D\include;${{ github.workspace }}\External\Siv3D\include\ThirdParty" `
            /p:LibraryPath="${{ github.workspace }}\External\Siv3D\lib\x64" `
            /p:CLAdditionalOptions="/DUNICODE /D_UNICODE /std:c++20"
